### ISSUE TITLE
spck setup ERROR

### ISSUE THREAD

**Issue by ShaneALMA** [rovelstars/spck-termux#2] opened 2022-06-20 00:05 UTC
![Screenshot_20220619-190338_Termux](https://user-images.githubusercontent.com/23668226/174505451-82681d61-aeb7-4f39-b3b5-8b02743f2c75.jpg)

**Comment by ShaneALMA** [comment] 2022-06-20 00:06
device Samsung galaxy a30s Android 11

**Comment by renhiyama** [comment] 2022-06-20 16:24
Duplicate of #1 . Try the method posted in that issue.

**Closed as completed by renhiyama** 2022-06-20 16:24 UTC
